### ISSUE TITLE
Dodać do REST-a "bilans miesiąca"

### ISSUE THREAD

**Issue by hlukasz** [sebah1989/workPresenceExpress#1]
Powinna być możliwość wyciągnięcia informacji ile nadgodzin/niedogodzin ma dany użytkownik w obecnym miesiącu. Przykładowo:
- 1.03 8 godzin
- 2.03 9 godzin
- 3.03 6 godzin

w dniu 4.04 bilans miesiąca wynosi -1 godzina
Oczywiście dokładność powinna być co do minuty i należy brać pod uwagę, że w weekendy się do pracy nie chodzi.

**Comment by sebah1989** [comment]
Done, dokładność co do sekundy :)

**Comment by hlukasz** [comment]
Się okaże :P
